import {Button, Form, Stack} from "react-bootstrap";

const MainChatWindow = () =>{
    return (<div className="flex-grow-1 message-box d-flex flex-column " style={{
            border: "1px solid #ccc",
            padding: "10px",
            borderRadius: "5px",
            overflowY: "auto",
            height: "550px"
        }}>

            <Stack direction="vertical" gap={3} className="justify-content-end">
                <div className="bubble bubble-left">Chat1</div>
                <div className="bubble bubble-right">Chat2</div>
                <div className="bubble bubble-left">Chat3 - pokus jestli resize ahoj ....................................
                    .......................................................
                    .......................
                </div>
                <div className="bubble bubble-right">Chat - pokus jestli resize ahoj ....................................
                    .......................................................
                    .......................
                </div>
                <div className="bubble bubble-left">Chat3 - pokus jestli resize ahoj ....................................
                    .......................................................
                    .......................
                </div>
                <div className="bubble bubble-right">Chat - pokus jestli resize ahoj ....................................
                    .......................................................
                    .......................
                </div>
                <div className="bubble bubble-left">Chat3 - pokus jestli resize ahoj ....................................
                    .......................................................
                    .......................
                </div>
                <div className="bubble bubble-right">Chat - pokus jestli resize ahoj ....................................
                    .......................................................
                    .......................
                </div>
                {/* Add more chat bubbles as needed */}
            </Stack>

            <Form className="position-sticky bottom-0">
                <Form.Group className="text-muted d-flex justify-content-start align-items-center pe-3 pt-3 mt-2">
                    <Form.Control type="text" placeholder="Type message"/>
                    <Button variant="primary" type="button">
                        Odeslat
                    </Button>
                </Form.Group>
            </Form>
        </div>
    )
}
export default MainChatWindow;